### ISSUE TITLE
Форматирование

### ISSUE THREAD

**Issue by itgirlschool** [AliaAlika/github-awarmwelcome-week-8#1]
Тег и внутренний тег на одном уровне.. Запускалось ли форматирование для этого файла ?)

https://github.com/AliaAlika/github-awarmwelcome-week-8/blob/aade65a299b9774ff8c025fc95d60e4ed119c7a5/awarmwelcome-week8.html#L22

**Comment by AliaAlika** [comment]
Запускалось (правда)) Но, видимо, не сработало
